FROM openjdk:11

ADD ./target/eureka-Implementation-0.0.1-SNAPSHOT.jar /usr/src/eureka-Implementation-0.0.1-SNAPSHOT.jar

WORKDIR usr/src

ENTRYPOINT ["java","-jar", "eureka-Implementation-0.0.1-SNAPSHOT.jar"]